# NOTE:  http://qiita.com/niisan-tokyo/items/2f4a0c904a7c6bfcc367
language: c

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
    - sudo apt-get update
    - sudo apt-get -y -q -o Dpkg::Options::="--force-confnew" install docker-engine
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

script:
    - docker-compose run mtest
